// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         skillId: "skillId"
 *     }
 */
export interface UpdateAiSkillRequest {
    aiId: string;
    skillId: string;
    name?: string;
    slug?: string;
    description?: string | null;
    category?: UpdateAiSkillRequest.Category;
    visibility?: UpdateAiSkillRequest.Visibility;
    instructions?: string;
    enabledActions?: string[];
    enabled?: boolean;
    metadata?: Record<string, unknown>;
}

export namespace UpdateAiSkillRequest {
    export const Category = {
        Ai: "ai",
        Human: "human",
        Hybrid: "hybrid",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
    export const Visibility = {
        Private: "PRIVATE",
        Public: "PUBLIC",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
