// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         transactionId: "transactionId",
 *         action: "CANCEL"
 *     }
 */
export interface TransactionActionRequest {
    transactionId: string;
    /** A caller-generated key, unique to this operation and payload. */
    "Idempotency-Key": string;
    action: TransactionActionRequest.Action;
    /** Optional partial refund amount. Omit to request the remaining refundable amount. */
    amountMinor?: number;
}

export namespace TransactionActionRequest {
    export const Action = {
        Cancel: "CANCEL",
        RequestRefund: "REQUEST_REFUND",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
}
