// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tool: "tool"
 *     }
 */
export interface ExecuteToolRequest {
    tool: string;
    input?: Record<string, unknown>;
}
