// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         toolkit: "toolkit",
 *         requestId: "requestId"
 *     }
 */
export interface CreateConnectionAuthorizationRequest {
    aiId: string;
    toolkit: string;
    requestId: string;
}
