// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         connectionId: "connectionId"
 *     }
 */
export interface RemoveAiConnectionRequest {
    aiId: string;
    connectionId: string;
}
