// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Darwin from "../../../index.js";

export declare namespace AisClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage canonical personal and business AI identities.
 */
export class AisClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AisClient.Options>;

    constructor(options: AisClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists skills that can be assigned to a personal or business AI. Assigned skills are managed on the AI.
     *
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.listSkillCatalog()
     */
    public listSkillCatalog(
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListSkillCatalogResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSkillCatalog(requestOptions));
    }

    private async __listSkillCatalog(
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListSkillCatalogResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "account/skills",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListSkillCatalogResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/account/skills");
    }

    /**
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.listAIs()
     */
    public listAIs(requestOptions?: AisClient.RequestOptions): core.HttpResponsePromise<Darwin.ListAIsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAIs(requestOptions));
    }

    private async __listAIs(
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListAIsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "ais",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListAIsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/ais");
    }

    /**
     * Every Darwin account already owns exactly one personal AI. This endpoint creates an additional business AI. A verified phone number may own up to three business AIs.
     *
     * @param {Darwin.CreateAiRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.createAi({
     *         name: "name"
     *     })
     */
    public createAi(
        request: Darwin.CreateAiRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.CreateAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAi(request, requestOptions));
    }

    private async __createAi(
        request: Darwin.CreateAiRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.CreateAiResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "ais",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.CreateAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/ais");
    }

    /**
     * @param {Darwin.GetAiRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.getAi({
     *         aiId: "aiId"
     *     })
     */
    public getAi(
        request: Darwin.GetAiRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.GetAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAi(request, requestOptions));
    }

    private async __getAi(
        request: Darwin.GetAiRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.GetAiResponse>> {
        const { aiId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.GetAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/ais/{aiId}");
    }

    /**
     * @param {Darwin.UpdateAiRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.updateAi({
     *         aiId: "aiId"
     *     })
     */
    public updateAi(
        request: Darwin.UpdateAiRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.UpdateAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateAi(request, requestOptions));
    }

    private async __updateAi(
        request: Darwin.UpdateAiRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.UpdateAiResponse>> {
        const { aiId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.UpdateAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/ais/{aiId}");
    }

    /**
     * @param {Darwin.ListAiAssetsRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.listAiAssets({
     *         aiId: "aiId"
     *     })
     */
    public listAiAssets(
        request: Darwin.ListAiAssetsRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListAiAssetsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAiAssets(request, requestOptions));
    }

    private async __listAiAssets(
        request: Darwin.ListAiAssetsRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListAiAssetsResponse>> {
        const { aiId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/assets`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListAiAssetsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/ais/{aiId}/assets");
    }

    /**
     * @param {Darwin.CreateAiAssetRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.createAiAsset({
     *         aiId: "aiId",
     *         title: "title",
     *         sourceUrl: "sourceUrl"
     *     })
     */
    public createAiAsset(
        request: Darwin.CreateAiAssetRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.CreateAiAssetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAiAsset(request, requestOptions));
    }

    private async __createAiAsset(
        request: Darwin.CreateAiAssetRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.CreateAiAssetResponse>> {
        const { aiId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/assets`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.CreateAiAssetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/ais/{aiId}/assets");
    }

    /**
     * @param {Darwin.BeginAiAssetUploadRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.beginAiAssetUpload({
     *         aiId: "aiId",
     *         title: "title",
     *         filename: "filename",
     *         mimeType: "mimeType",
     *         byteSize: 1
     *     })
     */
    public beginAiAssetUpload(
        request: Darwin.BeginAiAssetUploadRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.AiAssetUpload> {
        return core.HttpResponsePromise.fromPromise(this.__beginAiAssetUpload(request, requestOptions));
    }

    private async __beginAiAssetUpload(
        request: Darwin.BeginAiAssetUploadRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.AiAssetUpload>> {
        const { aiId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/assets/uploads`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.AiAssetUpload, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/ais/{aiId}/assets/uploads");
    }

    /**
     * @param {Darwin.CompleteAiAssetUploadRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.completeAiAssetUpload({
     *         aiId: "aiId",
     *         assetId: "assetId"
     *     })
     */
    public completeAiAssetUpload(
        request: Darwin.CompleteAiAssetUploadRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.CompleteAiAssetUploadResponse> {
        return core.HttpResponsePromise.fromPromise(this.__completeAiAssetUpload(request, requestOptions));
    }

    private async __completeAiAssetUpload(
        request: Darwin.CompleteAiAssetUploadRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.CompleteAiAssetUploadResponse>> {
        const { aiId, assetId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/assets/${core.url.encodePathParam(assetId)}/complete`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.CompleteAiAssetUploadResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/ais/{aiId}/assets/{assetId}/complete",
        );
    }

    /**
     * @param {Darwin.DeleteAiAssetRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.deleteAiAsset({
     *         aiId: "aiId",
     *         assetId: "assetId"
     *     })
     */
    public deleteAiAsset(
        request: Darwin.DeleteAiAssetRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.DeleteAiAssetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAiAsset(request, requestOptions));
    }

    private async __deleteAiAsset(
        request: Darwin.DeleteAiAssetRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.DeleteAiAssetResponse>> {
        const { aiId, assetId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/assets/${core.url.encodePathParam(assetId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.DeleteAiAssetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/ais/{aiId}/assets/{assetId}",
        );
    }

    /**
     * @param {Darwin.UpdateAiAssetRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.updateAiAsset({
     *         aiId: "aiId",
     *         assetId: "assetId"
     *     })
     */
    public updateAiAsset(
        request: Darwin.UpdateAiAssetRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.UpdateAiAssetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateAiAsset(request, requestOptions));
    }

    private async __updateAiAsset(
        request: Darwin.UpdateAiAssetRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.UpdateAiAssetResponse>> {
        const { aiId, assetId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/assets/${core.url.encodePathParam(assetId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.UpdateAiAssetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/ais/{aiId}/assets/{assetId}",
        );
    }

    /**
     * @param {Darwin.ListAiActivityRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.listAiActivity({
     *         aiId: "aiId"
     *     })
     */
    public listAiActivity(
        request: Darwin.ListAiActivityRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.AiActivityPage> {
        return core.HttpResponsePromise.fromPromise(this.__listAiActivity(request, requestOptions));
    }

    private async __listAiActivity(
        request: Darwin.ListAiActivityRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.AiActivityPage>> {
        const { aiId, limit, cursor } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            cursor,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/activity`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.AiActivityPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/ais/{aiId}/activity");
    }

    /**
     * @param {Darwin.ListAiMembersRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.listAiMembers({
     *         aiId: "aiId"
     *     })
     */
    public listAiMembers(
        request: Darwin.ListAiMembersRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListAiMembersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAiMembers(request, requestOptions));
    }

    private async __listAiMembers(
        request: Darwin.ListAiMembersRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListAiMembersResponse>> {
        const { aiId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/members`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListAiMembersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/ais/{aiId}/members");
    }

    /**
     * @param {Darwin.RemoveAiMemberRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.removeAiMember({
     *         aiId: "aiId",
     *         membershipId: "membershipId"
     *     })
     */
    public removeAiMember(
        request: Darwin.RemoveAiMemberRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.RemoveAiMemberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__removeAiMember(request, requestOptions));
    }

    private async __removeAiMember(
        request: Darwin.RemoveAiMemberRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.RemoveAiMemberResponse>> {
        const { aiId, membershipId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/members/${core.url.encodePathParam(membershipId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.RemoveAiMemberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/ais/{aiId}/members/{membershipId}",
        );
    }

    /**
     * Owner transfers remain an interactive Darwin-app workflow.
     *
     * @param {Darwin.UpdateAiMemberRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.updateAiMember({
     *         aiId: "aiId",
     *         membershipId: "membershipId",
     *         role: "admin"
     *     })
     */
    public updateAiMember(
        request: Darwin.UpdateAiMemberRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.UpdateAiMemberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateAiMember(request, requestOptions));
    }

    private async __updateAiMember(
        request: Darwin.UpdateAiMemberRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.UpdateAiMemberResponse>> {
        const { aiId, membershipId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/members/${core.url.encodePathParam(membershipId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.UpdateAiMemberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/ais/{aiId}/members/{membershipId}",
        );
    }

    /**
     * @param {Darwin.ListAiInvitationsRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.listAiInvitations({
     *         aiId: "aiId"
     *     })
     */
    public listAiInvitations(
        request: Darwin.ListAiInvitationsRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListAiInvitationsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAiInvitations(request, requestOptions));
    }

    private async __listAiInvitations(
        request: Darwin.ListAiInvitationsRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListAiInvitationsResponse>> {
        const { aiId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/invitations`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListAiInvitationsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/ais/{aiId}/invitations");
    }

    /**
     * @param {Darwin.CreateAiInvitationRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.createAiInvitation({
     *         aiId: "aiId",
     *         email: "email"
     *     })
     */
    public createAiInvitation(
        request: Darwin.CreateAiInvitationRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.CreateAiInvitationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAiInvitation(request, requestOptions));
    }

    private async __createAiInvitation(
        request: Darwin.CreateAiInvitationRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.CreateAiInvitationResponse>> {
        const { aiId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/invitations`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.CreateAiInvitationResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/ais/{aiId}/invitations");
    }

    /**
     * @param {Darwin.RevokeAiInvitationRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.revokeAiInvitation({
     *         aiId: "aiId",
     *         invitationId: "invitationId"
     *     })
     */
    public revokeAiInvitation(
        request: Darwin.RevokeAiInvitationRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.RevokeAiInvitationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__revokeAiInvitation(request, requestOptions));
    }

    private async __revokeAiInvitation(
        request: Darwin.RevokeAiInvitationRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.RevokeAiInvitationResponse>> {
        const { aiId, invitationId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/invitations/${core.url.encodePathParam(invitationId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.RevokeAiInvitationResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/ais/{aiId}/invitations/{invitationId}",
        );
    }

    /**
     * @param {Darwin.ListAccessPoliciesRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.listAccessPolicies({
     *         aiId: "aiId"
     *     })
     */
    public listAccessPolicies(
        request: Darwin.ListAccessPoliciesRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListAccessPoliciesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAccessPolicies(request, requestOptions));
    }

    private async __listAccessPolicies(
        request: Darwin.ListAccessPoliciesRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListAccessPoliciesResponse>> {
        const { aiId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/access-policies`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListAccessPoliciesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/ais/{aiId}/access-policies");
    }

    /**
     * Restricted policies support exact AIs, verified business attributes, and geography. Sensitive-trait targeting is rejected.
     *
     * @param {Darwin.CreateAccessPolicyRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.createAccessPolicy({
     *         aiId: "aiId",
     *         name: "name",
     *         visibility: "PUBLIC"
     *     })
     */
    public createAccessPolicy(
        request: Darwin.CreateAccessPolicyRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.CreateAccessPolicyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAccessPolicy(request, requestOptions));
    }

    private async __createAccessPolicy(
        request: Darwin.CreateAccessPolicyRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.CreateAccessPolicyResponse>> {
        const { aiId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/access-policies`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.CreateAccessPolicyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/ais/{aiId}/access-policies");
    }

    /**
     * @param {Darwin.UpdateAccessPolicyRequest} request
     * @param {AisClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.ais.updateAccessPolicy({
     *         aiId: "aiId",
     *         policyId: "policyId"
     *     })
     */
    public updateAccessPolicy(
        request: Darwin.UpdateAccessPolicyRequest,
        requestOptions?: AisClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.UpdateAccessPolicyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateAccessPolicy(request, requestOptions));
    }

    private async __updateAccessPolicy(
        request: Darwin.UpdateAccessPolicyRequest,
        requestOptions?: AisClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.UpdateAccessPolicyResponse>> {
        const { aiId, policyId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `ais/${core.url.encodePathParam(aiId)}/access-policies/${core.url.encodePathParam(policyId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.UpdateAccessPolicyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/ais/{aiId}/access-policies/{policyId}",
        );
    }
}
