// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface AccessPolicy {
    id: string;
    ownerAiId: string;
    name: string;
    visibility: Darwin.Visibility;
    naturalLanguage?: (string | null) | undefined;
    rules: Darwin.AccessPolicyRule[];
    compiledRules: Record<string, unknown>;
    version: number;
    previousVersionId?: (string | null) | undefined;
    status: AccessPolicy.Status;
    createdAt: string;
    updatedAt: string;
}

export namespace AccessPolicy {
    export const Status = {
        Active: "ACTIVE",
        Superseded: "SUPERSEDED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
