// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface AiBillingSummary {
    currency: AiBillingSummary.Currency;
    account: Darwin.AiBillingAccount;
    wallet: Darwin.AiWalletBalance;
    actions: AiBillingSummary.Actions;
    feePolicy: AiBillingSummary.FeePolicy;
}

export namespace AiBillingSummary {
    export const Currency = {
        Usd: "usd",
    } as const;
    export type Currency = (typeof Currency)[keyof typeof Currency];

    export interface Actions {
        canWithdraw: boolean;
        hasPaymentMethod: boolean;
        payoutReady: boolean;
    }

    export interface FeePolicy {
        standardPayout: Darwin.FeeRate;
        instantPayout: Darwin.FeeRate;
        instantPayoutIncludesStandardConnectCost: boolean;
    }
}
