// This file was auto-generated by Fern from our API Definition.

export interface AiMember {
    id: string;
    role: AiMember.Role;
    status: string;
    actionGrants?: string[] | undefined;
    user: AiMember.User;
}

export namespace AiMember {
    export const Role = {
        Owner: "owner",
        Admin: "admin",
        Member: "member",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];

    export interface User {
        id: string;
        name?: (string | null) | undefined;
        email: string;
        image?: (string | null) | undefined;
    }
}
