// This file was auto-generated by Fern from our API Definition.

export interface AiPermissions {
    aiId: string;
    visibility: AiPermissions.Visibility;
    profileAccessPolicyId: string | null;
    outboundAccessPolicyId: string | null;
    accessPolicies: Record<string, unknown>[];
}

export namespace AiPermissions {
    export const Visibility = {
        Public: "PUBLIC",
        Restricted: "RESTRICTED",
        Private: "PRIVATE",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
