// This file was auto-generated by Fern from our API Definition.

export interface AiReputation {
    aiId: string;
    tier: AiReputation.Tier;
    score: number;
    verifiedReliability: AiReputation.VerifiedReliability;
    incidentCount: number;
    updatedAt?: (string | null) | undefined;
}

export namespace AiReputation {
    export const Tier = {
        Excellent: "EXCELLENT",
        Strong: "STRONG",
        Established: "ESTABLISHED",
        Developing: "DEVELOPING",
    } as const;
    export type Tier = (typeof Tier)[keyof typeof Tier];

    export interface VerifiedReliability {
        completedTransactions: number;
        observedTransactions: number;
        reliabilityBps: number | null;
    }
}
