// This file was auto-generated by Fern from our API Definition.

export interface ApplicationWallet {
    applicationId: string;
    currency: string;
    availableAmountMinor: number;
    reservedAmountMinor: number;
    operationalAvailableAmountMinor: number;
    operationalReservedAmountMinor: number;
    pendingFeeEarningsMinor: number;
    availableFeeEarningsMinor: number;
}
