// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface CreateListingRequest {
    type: Darwin.ListingType;
    title: string;
    description?: (string | null) | undefined;
    status?: Darwin.ListingStatus | undefined;
    visibility?: Darwin.ListingVisibility | undefined;
    allowedAiIds?: string[] | undefined;
    category?: (string | null) | undefined;
    tags?: string[] | undefined;
    media?: Record<string, unknown>[] | undefined;
    pricing?: Darwin.ListingPricing | undefined;
    availability?: Record<string, unknown> | undefined;
    capacity?: Record<string, unknown> | undefined;
    attributes?: Record<string, unknown> | undefined;
    preferredDealTemplateKey?: (string | null) | undefined;
    supportedDealTemplateKeys?: string[] | undefined;
    sourceId?: (string | null) | undefined;
    externalRef?: (string | null) | undefined;
    variants?: Darwin.ListingVariant[] | undefined;
}
