// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface CreateGoalRequest {
    aiId?: string | undefined;
    title?: string | undefined;
    intent: string;
    mode?: Darwin.WorkMode | undefined;
    /** Deprecated compatibility representation. Use mode. */
    type?: CreateGoalRequest.Type | undefined;
    lifecycleStatus?: CreateGoalRequest.LifecycleStatus | undefined;
    visibility?: Darwin.Visibility | undefined;
    accessPolicyId?: string | undefined;
    cadence?: Record<string, unknown> | undefined;
    targeting?: Record<string, unknown> | undefined;
    context?: Record<string, unknown> | undefined;
}

export namespace CreateGoalRequest {
    /** Deprecated compatibility representation. Use mode. */
    export const Type = {
        Demand: "DEMAND",
        Supply: "SUPPLY",
        Chat: "CHAT",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const LifecycleStatus = {
        Draft: "DRAFT",
        Active: "ACTIVE",
    } as const;
    export type LifecycleStatus = (typeof LifecycleStatus)[keyof typeof LifecycleStatus];
}
