// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

/**
 * A customer-safe commercial work record. Darwin keeps matching, routing, and provider identifiers private.
 */
export interface Deal {
    id: string;
    aiId: string;
    /** Deprecated compatibility alias for goalId. */
    taskId?: (string | null) | undefined;
    goalId: string | null;
    mode: Deal.Mode;
    /** Deprecated compatibility field. Use mode. */
    direction: Deal.Direction;
    title: string;
    status: Deal.Status;
    visibility: Darwin.Visibility;
    accessPolicyId?: (string | null) | undefined;
    terms: Record<string, unknown>;
    counterparty: Record<string, unknown>;
    traceId?: (string | null) | undefined;
    sentAt?: (string | null) | undefined;
    respondedAt?: (string | null) | undefined;
    createdAt: string;
    updatedAt: string;
}

export namespace Deal {
    export const Mode = {
        Buy: "BUY",
        Sell: "SELL",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** Deprecated compatibility field. Use mode. */
    export const Direction = {
        Demand: "demand",
        Supply: "supply",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
    export const Status = {
        Draft: "draft",
        Sent: "sent",
        Accepted: "accepted",
        Rejected: "rejected",
        Withdrawn: "withdrawn",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
