// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface EnrollmentLink {
    id: string;
    applicationId: string;
    name?: string | undefined;
    codePrefix?: string | undefined;
    mode?: EnrollmentLink.Mode | undefined;
    defaultAiKind?: EnrollmentLink.DefaultAiKind | undefined;
    defaultVisibility?: Darwin.Visibility | undefined;
    maxUses?: (number | null) | undefined;
    useCount?: number | undefined;
    expiresAt?: (string | null) | undefined;
    revokedAt?: (string | null) | undefined;
    settings?: Record<string, unknown> | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}

export namespace EnrollmentLink {
    export const Mode = {
        Hosted: "HOSTED",
        Embedded: "EMBEDDED",
        Hybrid: "HYBRID",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    export const DefaultAiKind = {
        Personal: "PERSONAL",
        Business: "BUSINESS",
    } as const;
    export type DefaultAiKind = (typeof DefaultAiKind)[keyof typeof DefaultAiKind];
}
