// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface EphemeralGoal {
    id: string;
    goalId: string;
    externalUserReference: string;
    accountablePrincipal: EphemeralGoal.AccountablePrincipal;
    mode: Darwin.WorkMode;
    title?: string | undefined;
    intent: string;
    status: EphemeralGoal.Status;
    castAt?: (string | null) | undefined;
    expiresAt: string;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace EphemeralGoal {
    export interface AccountablePrincipal {
        type: AccountablePrincipal.Type;
        applicationId: string;
    }

    export namespace AccountablePrincipal {
        export const Type = {
            Application: "application",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];
    }

    export const Status = {
        Draft: "draft",
        Cast: "cast",
        Matched: "matched",
        Claimed: "claimed",
        Canceled: "canceled",
        Expired: "expired",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
