// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    statusCode?: number | undefined;
    message?: Error_.Message | undefined;
    error?: string | undefined;
}

export namespace Error_ {
    export type Message = string | string[];
}
