// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface Goal {
    id: string;
    /** Canonical Goal identifier. Equal to id. */
    goalId: string;
    aiId: string;
    title: string;
    intent: string;
    mode: Darwin.WorkMode;
    /** Deprecated compatibility representation. Use mode. */
    type: Goal.Type;
    lifecycleStatus: Goal.LifecycleStatus;
    publicationStatus: Goal.PublicationStatus;
    visibility: Darwin.Visibility;
    accessPolicyId?: (string | null) | undefined;
    pausedUntil?: (string | null) | undefined;
    archivedAt?: (string | null) | undefined;
    cadence: Record<string, unknown>;
    targeting: Record<string, unknown>;
    context: Record<string, unknown>;
    listingIds?: string[] | undefined;
    dealTemplateKey?: (string | null) | undefined;
    publication?: (Record<string, unknown> | null) | undefined;
    createdAt: string;
    updatedAt: string;
}

export namespace Goal {
    /** Deprecated compatibility representation. Use mode. */
    export const Type = {
        Demand: "DEMAND",
        Supply: "SUPPLY",
        Chat: "CHAT",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const LifecycleStatus = {
        Draft: "DRAFT",
        Active: "ACTIVE",
        Paused: "PAUSED",
        Completed: "COMPLETED",
        Archived: "ARCHIVED",
    } as const;
    export type LifecycleStatus = (typeof LifecycleStatus)[keyof typeof LifecycleStatus];
    export const PublicationStatus = {
        NotPublished: "NOT_PUBLISHED",
        Requested: "REQUESTED",
        Publishing: "PUBLISHING",
        Published: "PUBLISHED",
        Failed: "FAILED",
    } as const;
    export type PublicationStatus = (typeof PublicationStatus)[keyof typeof PublicationStatus];
}
