// This file was auto-generated by Fern from our API Definition.

export interface Integrations {
    catalog: Integrations.Catalog;
    connections: Record<string, unknown>[];
    skills: Record<string, unknown>[];
}

export namespace Integrations {
    export interface Catalog {
        enabled: boolean;
        toolkits: Record<string, unknown>[];
    }
}
