// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface NetworkBrowseResult {
    network: NetworkBrowseResult.Network;
    category: Darwin.NetworkCategory | null;
    trending: Darwin.NetworkAiCard[];
    generatedAt: string;
}

export namespace NetworkBrowseResult {
    export interface Network {
        aiCount: number;
        activePublicListingCount: number;
        activePublicSkillCount: number;
        categories: Darwin.NetworkCategory[];
        updatedAt: string;
    }
}
