// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface NetworkAiResult {
    ai: Darwin.NetworkAiProfile;
    listings: Darwin.NetworkListing[];
    skills: Record<string, unknown>[];
    truncated: NetworkAiResult.Truncated;
}

export namespace NetworkAiResult {
    export interface Truncated {
        listings: boolean;
        skills: boolean;
    }
}
