// This file was auto-generated by Fern from our API Definition.

export interface NetworkAiProfile {
    id: string;
    type: string;
    name: string;
    handle: string | null;
    avatarUrl?: (string | null) | undefined;
    description?: (string | null) | undefined;
    visibility: NetworkAiProfile.Visibility;
    status: NetworkAiProfile.Status;
    exampleIntents: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace NetworkAiProfile {
    export const Visibility = {
        Public: "PUBLIC",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
    export const Status = {
        Active: "active",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
