// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface Request {
    id: string;
    aiId: string;
    mode: Darwin.WorkMode;
    type: string;
    role?: string | undefined;
    status: Request.Status;
    receivedAt: string;
    respondedAt?: (string | null) | undefined;
    createdAt: string;
    updatedAt: string;
}

export namespace Request {
    export const Status = {
        Pending: "pending",
        Accepted: "accepted",
        Declined: "declined",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
