// This file was auto-generated by Fern from our API Definition.

export interface ServiceAccount {
    id: string;
    applicationId?: string | undefined;
    name?: string | undefined;
    keyPrefix?: string | undefined;
    prefix?: string | undefined;
    scopes?: ServiceAccount.Scopes.Item[] | undefined;
    status: ServiceAccount.Status;
    requestCount?: number | undefined;
    lastUsedAt?: (string | null) | undefined;
    expiresAt?: (string | null) | undefined;
    revokedAt?: (string | null) | undefined;
    createdAt?: string | undefined;
}

export namespace ServiceAccount {
    export type Scopes = Scopes.Item[];

    export namespace Scopes {
        export const Item = {
            AisRead: "ais:read",
            AisWrite: "ais:write",
            MembersRead: "members:read",
            ConversationsRead: "conversations:read",
            ConversationsWrite: "conversations:write",
            RequestsRead: "requests:read",
            RequestsWrite: "requests:write",
            AiRead: "ai:read",
            AiWrite: "ai:write",
            TasksRead: "tasks:read",
            TasksWrite: "tasks:write",
            GoalsRead: "goals:read",
            GoalsWrite: "goals:write",
            DealsRead: "deals:read",
            DealsWrite: "deals:write",
            TransactionsRead: "transactions:read",
            OutcomesRead: "outcomes:read",
            OutcomesWrite: "outcomes:write",
            IntegrationsRead: "integrations:read",
            ConnectionsRead: "connections:read",
            PermissionsRead: "permissions:read",
            ReputationRead: "reputation:read",
            SkillsRead: "skills:read",
            ListingsRead: "listings:read",
            ListingsWrite: "listings:write",
            NotificationsRead: "notifications:read",
            UsageRead: "usage:read",
            VerificationRead: "verification:read",
            DeploymentRead: "deployment:read",
            EphemeralGoalsRead: "ephemeral-goals:read",
            EphemeralGoalsWrite: "ephemeral-goals:write",
            EphemeralTasksRead: "ephemeral-tasks:read",
            EphemeralTasksWrite: "ephemeral-tasks:write",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    export const Status = {
        Active: "ACTIVE",
        Revoked: "REVOKED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
