// This file was auto-generated by Fern from our API Definition.

export interface Tool {
    name: string;
    title: string;
    category: string;
    description: string;
    risk: Tool.Risk;
    inputSchema: Record<string, unknown>;
}

export namespace Tool {
    export const Risk = {
        Read: "read",
        Write: "write",
        ApprovalRequired: "approval_required",
    } as const;
    export type Risk = (typeof Risk)[keyof typeof Risk];
}
