// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface TransactionFundingResult {
    state: TransactionFundingResult.State;
    transaction: Darwin.Transaction;
    fundingAmountMinor?: number | undefined;
    fundingRail?: (string | null) | undefined;
    clientSecret?: (string | null) | undefined;
}

export namespace TransactionFundingResult {
    export const State = {
        Ready: "ready",
        RequiresFunding: "requires_funding",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
