// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface UpdateGoalRequest {
    title?: string | undefined;
    intent?: string | undefined;
    mode?: Darwin.WorkMode | undefined;
    /** Deprecated compatibility representation. Use mode. */
    type?: UpdateGoalRequest.Type | undefined;
    lifecycleStatus?: UpdateGoalRequest.LifecycleStatus | undefined;
    visibility?: Darwin.Visibility | undefined;
    accessPolicyId?: (string | null) | undefined;
    pausedUntil?: (string | null) | undefined;
    cadence?: Record<string, unknown> | undefined;
    targeting?: Record<string, unknown> | undefined;
    context?: Record<string, unknown> | undefined;
}

export namespace UpdateGoalRequest {
    /** Deprecated compatibility representation. Use mode. */
    export const Type = {
        Demand: "DEMAND",
        Supply: "SUPPLY",
        Chat: "CHAT",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const LifecycleStatus = {
        Draft: "DRAFT",
        Active: "ACTIVE",
        Paused: "PAUSED",
        Completed: "COMPLETED",
        Archived: "ARCHIVED",
    } as const;
    export type LifecycleStatus = (typeof LifecycleStatus)[keyof typeof LifecycleStatus];
}
