// This file was auto-generated by Fern from our API Definition.

export const Visibility = {
    Public: "PUBLIC",
    Restricted: "RESTRICTED",
    Private: "PRIVATE",
} as const;
export type Visibility = (typeof Visibility)[keyof typeof Visibility];
