// This file was auto-generated by Fern from our API Definition.

export interface Webhook {
    id: string;
    applicationId?: string | undefined;
    url?: string | undefined;
    events?: string[] | undefined;
    status: Webhook.Status;
    secretPrefix?: string | undefined;
    lastDeliveredAt?: (string | null) | undefined;
    lastFailureAt?: (string | null) | undefined;
    failureCount?: number | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}

export namespace Webhook {
    export const Status = {
        Active: "ACTIVE",
        Revoked: "REVOKED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
