// This file was auto-generated by Fern from our API Definition.

export interface WithdrawalRequest {
    amountMinor: number;
    speed?: WithdrawalRequest.Speed | undefined;
}

export namespace WithdrawalRequest {
    export const Speed = {
        Standard: "standard",
        Instant: "instant",
    } as const;
    export type Speed = (typeof Speed)[keyof typeof Speed];
}
