// This file was auto-generated by Fern from our API Definition.

/** The workflow view for shared Darwin work resources. */
export const WorkMode = {
    Buy: "BUY",
    Sell: "SELL",
    Chat: "CHAT",
} as const;
export type WorkMode = (typeof WorkMode)[keyof typeof WorkMode];
