// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../index.js";

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         listingId: "listingId",
 *         expectedRevision: 1
 *     }
 */
export interface UpdateListingRequest {
    aiId: string;
    listingId: string;
    expectedRevision: number;
    type?: Darwin.ListingType;
    title?: string;
    description?: string | null;
    status?: Darwin.ListingStatus;
    visibility?: Darwin.ListingVisibility;
    allowedAiIds?: string[];
    category?: string | null;
    tags?: string[];
    media?: Record<string, unknown>[];
    pricing?: Darwin.ListingPricing;
    availability?: Record<string, unknown>;
    capacity?: Record<string, unknown>;
    attributes?: Record<string, unknown>;
    preferredDealTemplateKey?: string | null;
    supportedDealTemplateKeys?: string[];
    sourceId?: string | null;
    externalRef?: string | null;
    variants?: Darwin.ListingVariant[];
}
