// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Darwin from "../../../index.js";

export declare namespace ApprovalsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Review decisions requested by the agent selected on the developer/MCP channel.
 */
export class ApprovalsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ApprovalsClient.Options>;

    constructor(options: ApprovalsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Darwin.ListApprovalsRequest} request
     * @param {ApprovalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.approvals.listApprovals()
     */
    public listApprovals(
        request: Darwin.ListApprovalsRequest = {},
        requestOptions?: ApprovalsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListApprovalsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listApprovals(request, requestOptions));
    }

    private async __listApprovals(
        request: Darwin.ListApprovalsRequest = {},
        requestOptions?: ApprovalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListApprovalsResponse>> {
        const { status } = request;
        const _queryParams: Record<string, unknown> = {
            status,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "approvals",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListApprovalsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/approvals");
    }

    /**
     * @param {Darwin.ApprovalDecisionRequest} request
     * @param {ApprovalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.approvals.decideApproval({
     *         id: "id",
     *         decision: "APPROVE"
     *     })
     */
    public decideApproval(
        request: Darwin.ApprovalDecisionRequest,
        requestOptions?: ApprovalsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__decideApproval(request, requestOptions));
    }

    private async __decideApproval(
        request: Darwin.ApprovalDecisionRequest,
        requestOptions?: ApprovalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `approvals/${core.url.encodePathParam(id)}/decisions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/approvals/{id}/decisions");
    }
}
