// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../index.js";

/**
 * @example
 *     {
 *         mode: "BUY",
 *         title: "title"
 *     }
 */
export interface CreateDealRequest {
    /** Optional explicit AI scope. When omitted, Darwin uses the caller’s selected AI. */
    aiId?: string;
    goalId?: string;
    /** Deprecated compatibility alias for goalId. */
    taskId?: string;
    mode: CreateDealRequest.Mode;
    /** Deprecated compatibility field. Use mode. */
    direction?: CreateDealRequest.Direction;
    title: string;
    visibility?: Darwin.Visibility;
    accessPolicyId?: string;
    terms?: Record<string, unknown>;
    counterparty?: Record<string, unknown>;
    listingSelections?: Darwin.ListingSelection[];
}

export namespace CreateDealRequest {
    export const Mode = {
        Buy: "BUY",
        Sell: "SELL",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** Deprecated compatibility field. Use mode. */
    export const Direction = {
        Demand: "DEMAND",
        Supply: "SUPPLY",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
}
