// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../index.js";

/**
 * @example
 *     {
 *         dealId: "dealId"
 *     }
 */
export interface UpdateDealRequest {
    dealId: string;
    title?: string;
    visibility?: Darwin.Visibility;
    accessPolicyId?: string | null;
    terms?: Record<string, unknown>;
    counterparty?: Record<string, unknown>;
}
