// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         title: "title",
 *         sourceUrl: "sourceUrl"
 *     }
 */
export interface CreateAiAssetRequest {
    aiId: string;
    title: string;
    description?: string | null;
    kind?: CreateAiAssetRequest.Kind;
    sourceUrl: string;
    previewUrl?: string;
    visibility?: CreateAiAssetRequest.Visibility;
    metadata?: Record<string, unknown>;
}

export namespace CreateAiAssetRequest {
    export const Kind = {
        Image: "image",
        Video: "video",
        Audio: "audio",
        Document: "document",
        Data: "data",
        Link: "link",
        Other: "other",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
    export const Visibility = {
        Private: "PRIVATE",
        Public: "PUBLIC",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
