// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../index.js";

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         name: "name",
 *         visibility: "PUBLIC"
 *     }
 */
export interface CreateAccessPolicyRequest {
    aiId: string;
    name: string;
    visibility: Darwin.Visibility;
    naturalLanguage?: string;
    rules?: Darwin.AccessPolicyRule[];
}
