// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         invitationId: "invitationId"
 *     }
 */
export interface RevokeAiInvitationRequest {
    aiId: string;
    invitationId: string;
}
