// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         membershipId: "membershipId",
 *         role: "admin"
 *     }
 */
export interface UpdateAiMemberRequest {
    aiId: string;
    membershipId: string;
    role: UpdateAiMemberRequest.Role;
}

export namespace UpdateAiMemberRequest {
    export const Role = {
        Admin: "admin",
        Member: "member",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
