// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         assetId: "assetId"
 *     }
 */
export interface UpdateAiAssetRequest {
    aiId: string;
    assetId: string;
    title?: string;
    description?: string | null;
    visibility?: UpdateAiAssetRequest.Visibility;
    metadata?: Record<string, unknown>;
}

export namespace UpdateAiAssetRequest {
    export const Visibility = {
        Private: "PRIVATE",
        Public: "PUBLIC",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
