// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Darwin from "../../../index.js";

export declare namespace GoalsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Create and manage the durable outcomes an AI pursues across buy, sell, and chat.
 */
export class GoalsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<GoalsClient.Options>;

    constructor(options: GoalsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Darwin.ListGoalsRequest} request
     * @param {GoalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.goals.listGoals()
     */
    public listGoals(
        request: Darwin.ListGoalsRequest = {},
        requestOptions?: GoalsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListGoalsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listGoals(request, requestOptions));
    }

    private async __listGoals(
        request: Darwin.ListGoalsRequest = {},
        requestOptions?: GoalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListGoalsResponse>> {
        const { aiId, mode } = request;
        const _queryParams: Record<string, unknown> = {
            aiId,
            mode: mode != null ? mode : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "goals",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListGoalsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/goals");
    }

    /**
     * @param {Darwin.CreateGoalRequest} request
     * @param {GoalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.goals.createGoal({
     *         intent: "intent"
     *     })
     */
    public createGoal(
        request: Darwin.CreateGoalRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.CreateGoalResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createGoal(request, requestOptions));
    }

    private async __createGoal(
        request: Darwin.CreateGoalRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.CreateGoalResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "goals",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.CreateGoalResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/goals");
    }

    /**
     * @param {Darwin.GetGoalRequest} request
     * @param {GoalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.goals.getGoal({
     *         id: "id"
     *     })
     */
    public getGoal(
        request: Darwin.GetGoalRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.GetGoalResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getGoal(request, requestOptions));
    }

    private async __getGoal(
        request: Darwin.GetGoalRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.GetGoalResponse>> {
        const { id, aiId } = request;
        const _queryParams: Record<string, unknown> = {
            aiId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `goals/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.GetGoalResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/goals/{id}");
    }

    /**
     * @param {Darwin.UpdateGoalBody} request
     * @param {GoalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.goals.updateGoal({
     *         id: "id",
     *         body: {}
     *     })
     */
    public updateGoal(
        request: Darwin.UpdateGoalBody,
        requestOptions?: GoalsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.UpdateGoalResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateGoal(request, requestOptions));
    }

    private async __updateGoal(
        request: Darwin.UpdateGoalBody,
        requestOptions?: GoalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.UpdateGoalResponse>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `goals/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.UpdateGoalResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/goals/{id}");
    }

    /**
     * Draft goals can activate; active goals can pause or complete; paused goals can resume or complete; completed goals can archive. Completion is blocked while negotiations, transactions, or recurring agreements remain active.
     *
     * @param {Darwin.ActOnGoalRequest} request
     * @param {GoalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.goals.actOnGoal({
     *         id: "id",
     *         body: {
     *             action: "PAUSE"
     *         }
     *     })
     */
    public actOnGoal(
        request: Darwin.ActOnGoalRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ActOnGoalResponse> {
        return core.HttpResponsePromise.fromPromise(this.__actOnGoal(request, requestOptions));
    }

    private async __actOnGoal(
        request: Darwin.ActOnGoalRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ActOnGoalResponse>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `goals/${core.url.encodePathParam(id)}/actions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ActOnGoalResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/goals/{id}/actions");
    }

    /**
     * Creates an actionable request to publish a private goal. Darwin does not publish the goal until the account resolves the request.
     *
     * @param {Darwin.RequestGoalPublicationRequest} request
     * @param {GoalsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.goals.requestGoalPublication({
     *         id: "id",
     *         body: {}
     *     })
     */
    public requestGoalPublication(
        request: Darwin.RequestGoalPublicationRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.PublicationRequestResult> {
        return core.HttpResponsePromise.fromPromise(this.__requestGoalPublication(request, requestOptions));
    }

    private async __requestGoalPublication(
        request: Darwin.RequestGoalPublicationRequest,
        requestOptions?: GoalsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.PublicationRequestResult>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `goals/${core.url.encodePathParam(id)}/publication-requests`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.PublicationRequestResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/goals/{id}/publication-requests",
        );
    }
}
