// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../src/api/index";
import { DarwinClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ApplicationsClient", () => {
    test("listApplications (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            applications: [
                {
                    id: "id",
                    name: "name",
                    slug: "slug",
                    description: "description",
                    websiteUrl: "websiteUrl",
                    mode: "hosted",
                    status: "active",
                    redirectUris: ["redirectUris"],
                    defaultAiKind: "personal",
                    defaultVisibility: "PUBLIC",
                    oauth: {
                        clientId: "clientId",
                        authorizationUrl: "authorizationUrl",
                        tokenUrl: "tokenUrl",
                        requirePKCE: true,
                    },
                    metadata: { key: "value" },
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/applications").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.applications.listApplications();
        expect(response).toEqual(rawResponseBody);
    });

    test("listApplications (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.applications.listApplications();
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listApplications (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.applications.listApplications();
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listApplications (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.applications.listApplications();
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listApplications (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.applications.listApplications();
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.createApplication({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.getApplication({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("archiveApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.archiveApplication({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("archiveApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("archiveApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("archiveApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("archiveApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("updateApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.updateApplication({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("updateApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("updateApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("updateApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("listApplicationAIs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            ais: [
                {
                    id: "id",
                    applicationId: "applicationId",
                    aiId: "aiId",
                    externalReference: "externalReference",
                    status: "ACTIVE",
                    visibility: "PUBLIC",
                    permissions: ["permissions"],
                    metadata: { key: "value" },
                    linkedAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.listApplicationAIs({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listApplicationAIs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listApplicationAIs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listApplicationAIs (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listApplicationAIs (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("linkApplicationAI (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {
            aiLink: {
                id: "id",
                applicationId: "applicationId",
                aiId: "aiId",
                externalReference: "externalReference",
                status: "ACTIVE",
                visibility: "PUBLIC",
                permissions: ["permissions"],
                metadata: { key: "value" },
                linkedAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                aiIdentity: {
                    id: "id",
                    kind: "PERSONAL",
                    name: "name",
                    handle: "handle",
                    avatarUrl: "avatarUrl",
                    description: "description",
                    visibility: "PUBLIC",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.linkApplicationAi({
            applicationId: "applicationId",
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("linkApplicationAI (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("linkApplicationAI (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("linkApplicationAI (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("linkApplicationAI (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("unlinkApplicationAI (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            aiLink: {
                id: "id",
                applicationId: "applicationId",
                aiId: "aiId",
                externalReference: "externalReference",
                status: "ACTIVE",
                visibility: "PUBLIC",
                permissions: ["permissions"],
                metadata: { key: "value" },
                linkedAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                aiIdentity: {
                    id: "id",
                    kind: "PERSONAL",
                    name: "name",
                    handle: "handle",
                    avatarUrl: "avatarUrl",
                    description: "description",
                    visibility: "PUBLIC",
                },
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.unlinkApplicationAi({
            applicationId: "applicationId",
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("unlinkApplicationAI (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("unlinkApplicationAI (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("unlinkApplicationAI (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("unlinkApplicationAI (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("listEnrollmentLinks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            enrollmentLinks: [
                {
                    id: "id",
                    applicationId: "applicationId",
                    name: "name",
                    codePrefix: "codePrefix",
                    mode: "HOSTED",
                    defaultAiKind: "PERSONAL",
                    defaultVisibility: "PUBLIC",
                    maxUses: 1,
                    useCount: 1,
                    expiresAt: "2024-01-15T09:30:00Z",
                    revokedAt: "2024-01-15T09:30:00Z",
                    settings: { key: "value" },
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.listEnrollmentLinks({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listEnrollmentLinks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listEnrollmentLinks (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listEnrollmentLinks (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listEnrollmentLinks (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createEnrollmentLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            enrollmentLink: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                codePrefix: "codePrefix",
                mode: "HOSTED",
                defaultAiKind: "PERSONAL",
                defaultVisibility: "PUBLIC",
                maxUses: 1,
                useCount: 1,
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                settings: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                token: "token",
                url: "url",
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.createEnrollmentLink({
            applicationId: "applicationId",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createEnrollmentLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createEnrollmentLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createEnrollmentLink (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createEnrollmentLink (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("revokeEnrollmentLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            enrollmentLink: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                codePrefix: "codePrefix",
                mode: "HOSTED",
                defaultAiKind: "PERSONAL",
                defaultVisibility: "PUBLIC",
                maxUses: 1,
                useCount: 1,
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                settings: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.revokeEnrollmentLink({
            applicationId: "applicationId",
            enrollmentLinkId: "enrollmentLinkId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("revokeEnrollmentLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("revokeEnrollmentLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("revokeEnrollmentLink (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("revokeEnrollmentLink (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getApplicationWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            wallet: {
                applicationId: "applicationId",
                currency: "currency",
                availableAmountMinor: 1,
                reservedAmountMinor: 1,
                operationalAvailableAmountMinor: 1,
                operationalReservedAmountMinor: 1,
                pendingFeeEarningsMinor: 1,
                availableFeeEarningsMinor: 1,
            },
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.getApplicationWallet({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getApplicationWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getApplicationWallet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getApplicationWallet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getApplicationWallet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("fundApplicationWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "currency" };
        const rawResponseBody = {
            wallet: {
                applicationId: "applicationId",
                currency: "currency",
                availableAmountMinor: 1,
                reservedAmountMinor: 1,
                operationalAvailableAmountMinor: 1,
                operationalReservedAmountMinor: 1,
                pendingFeeEarningsMinor: 1,
                availableFeeEarningsMinor: 1,
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.fundApplicationWallet({
            "Idempotency-Key": "Idempotency-Key",
            applicationId: "applicationId",
            aiId: "aiId",
            amountMinor: 1,
            currency: "currency",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("fundApplicationWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("fundApplicationWallet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("fundApplicationWallet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("fundApplicationWallet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("listServiceAccounts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            serviceAccounts: [
                {
                    id: "id",
                    applicationId: "applicationId",
                    name: "name",
                    keyPrefix: "keyPrefix",
                    prefix: "prefix",
                    scopes: ["ais:read"],
                    status: "ACTIVE",
                    requestCount: 1,
                    lastUsedAt: "2024-01-15T09:30:00Z",
                    expiresAt: "2024-01-15T09:30:00Z",
                    revokedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.listServiceAccounts({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listServiceAccounts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listServiceAccounts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listServiceAccounts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listServiceAccounts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createServiceAccount (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            serviceAccount: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                keyPrefix: "keyPrefix",
                prefix: "prefix",
                scopes: ["ais:read"],
                status: "ACTIVE",
                requestCount: 1,
                lastUsedAt: "2024-01-15T09:30:00Z",
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                apiKey: "apiKey",
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.createServiceAccount({
            applicationId: "applicationId",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createServiceAccount (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createServiceAccount (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createServiceAccount (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createServiceAccount (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("revokeServiceAccount (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            serviceAccount: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                keyPrefix: "keyPrefix",
                prefix: "prefix",
                scopes: ["ais:read"],
                status: "ACTIVE",
                requestCount: 1,
                lastUsedAt: "2024-01-15T09:30:00Z",
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.applications.revokeServiceAccount({
            applicationId: "applicationId",
            serviceAccountId: "serviceAccountId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("revokeServiceAccount (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("revokeServiceAccount (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("revokeServiceAccount (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("revokeServiceAccount (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
