// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../src/api/index";
import { DarwinClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ListingsClient", () => {
    test("listListings (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            listings: [
                {
                    id: "id",
                    aiId: "aiId",
                    type: "PRODUCT",
                    title: "title",
                    description: "description",
                    category: "category",
                    tags: ["tags"],
                    media: [{ key: "value" }],
                    status: "DRAFT",
                    visibility: "PUBLIC",
                    allowedAiIds: ["allowedAiIds"],
                    availability: { key: "value" },
                    capacity: { key: "value" },
                    attributes: { key: "value" },
                    preferredDealTemplateKey: "preferredDealTemplateKey",
                    supportedDealTemplateKeys: ["supportedDealTemplateKeys"],
                    sourceId: "sourceId",
                    externalRef: "externalRef",
                    variants: [{ id: "id", title: "title", status: "DRAFT" }],
                    revision: 1,
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            nextCursor: "nextCursor",
        };

        server.mockEndpoint().get("/ais/aiId/listings").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.listings.listListings({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listListings (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/listings").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.listings.listListings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listListings (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/listings").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.listings.listListings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listListings (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/listings").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.listings.listListings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listListings (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/listings").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.listings.listListings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createListing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "PRODUCT", title: "title" };
        const rawResponseBody = {
            listing: {
                id: "id",
                aiId: "aiId",
                type: "PRODUCT",
                title: "title",
                description: "description",
                category: "category",
                tags: ["tags"],
                media: [{ key: "value" }],
                status: "DRAFT",
                visibility: "PUBLIC",
                allowedAiIds: ["allowedAiIds"],
                pricing: {
                    mode: "FREE",
                    currency: "currency",
                    amountMinor: 1,
                    minimumAmountMinor: 1,
                    maximumAmountMinor: 1,
                    unit: "unit",
                    interval: "interval",
                },
                availability: { key: "value" },
                capacity: { key: "value" },
                attributes: { key: "value" },
                preferredDealTemplateKey: "preferredDealTemplateKey",
                supportedDealTemplateKeys: ["supportedDealTemplateKeys"],
                sourceId: "sourceId",
                externalRef: "externalRef",
                variants: [{ id: "id", title: "title", status: "DRAFT" }],
                revision: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/ais/aiId/listings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.listings.createListing({
            aiId: "aiId",
            body: {
                type: "PRODUCT",
                title: "title",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createListing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "PRODUCT", title: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListing({
                aiId: "aiId",
                body: {
                    type: "PRODUCT",
                    title: "x",
                },
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createListing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "PRODUCT", title: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListing({
                aiId: "aiId",
                body: {
                    type: "PRODUCT",
                    title: "x",
                },
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createListing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "PRODUCT", title: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListing({
                aiId: "aiId",
                body: {
                    type: "PRODUCT",
                    title: "x",
                },
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createListing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "PRODUCT", title: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListing({
                aiId: "aiId",
                body: {
                    type: "PRODUCT",
                    title: "x",
                },
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getListing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            listing: {
                id: "id",
                aiId: "aiId",
                type: "PRODUCT",
                title: "title",
                description: "description",
                category: "category",
                tags: ["tags"],
                media: [{ key: "value" }],
                status: "DRAFT",
                visibility: "PUBLIC",
                allowedAiIds: ["allowedAiIds"],
                pricing: {
                    mode: "FREE",
                    currency: "currency",
                    amountMinor: 1,
                    minimumAmountMinor: 1,
                    maximumAmountMinor: 1,
                    unit: "unit",
                    interval: "interval",
                },
                availability: { key: "value" },
                capacity: { key: "value" },
                attributes: { key: "value" },
                preferredDealTemplateKey: "preferredDealTemplateKey",
                supportedDealTemplateKeys: ["supportedDealTemplateKeys"],
                sourceId: "sourceId",
                externalRef: "externalRef",
                variants: [{ id: "id", title: "title", status: "DRAFT" }],
                revision: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.listings.getListing({
            aiId: "aiId",
            listingId: "listingId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getListing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.getListing({
                aiId: "aiId",
                listingId: "listingId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getListing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.getListing({
                aiId: "aiId",
                listingId: "listingId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getListing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.getListing({
                aiId: "aiId",
                listingId: "listingId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getListing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.getListing({
                aiId: "aiId",
                listingId: "listingId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("archiveListing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            listing: {
                id: "id",
                aiId: "aiId",
                type: "PRODUCT",
                title: "title",
                description: "description",
                category: "category",
                tags: ["tags"],
                media: [{ key: "value" }],
                status: "DRAFT",
                visibility: "PUBLIC",
                allowedAiIds: ["allowedAiIds"],
                pricing: {
                    mode: "FREE",
                    currency: "currency",
                    amountMinor: 1,
                    minimumAmountMinor: 1,
                    maximumAmountMinor: 1,
                    unit: "unit",
                    interval: "interval",
                },
                availability: { key: "value" },
                capacity: { key: "value" },
                attributes: { key: "value" },
                preferredDealTemplateKey: "preferredDealTemplateKey",
                supportedDealTemplateKeys: ["supportedDealTemplateKeys"],
                sourceId: "sourceId",
                externalRef: "externalRef",
                variants: [{ id: "id", title: "title", status: "DRAFT" }],
                revision: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.listings.archiveListing({
            aiId: "aiId",
            listingId: "listingId",
            expectedRevision: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("archiveListing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.archiveListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("archiveListing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.archiveListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("archiveListing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.archiveListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("archiveListing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/listings/listingId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.archiveListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("updateListing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { expectedRevision: 1 };
        const rawResponseBody = {
            listing: {
                id: "id",
                aiId: "aiId",
                type: "PRODUCT",
                title: "title",
                description: "description",
                category: "category",
                tags: ["tags"],
                media: [{ key: "value" }],
                status: "DRAFT",
                visibility: "PUBLIC",
                allowedAiIds: ["allowedAiIds"],
                pricing: {
                    mode: "FREE",
                    currency: "currency",
                    amountMinor: 1,
                    minimumAmountMinor: 1,
                    maximumAmountMinor: 1,
                    unit: "unit",
                    interval: "interval",
                },
                availability: { key: "value" },
                capacity: { key: "value" },
                attributes: { key: "value" },
                preferredDealTemplateKey: "preferredDealTemplateKey",
                supportedDealTemplateKeys: ["supportedDealTemplateKeys"],
                sourceId: "sourceId",
                externalRef: "externalRef",
                variants: [{ id: "id", title: "title", status: "DRAFT" }],
                revision: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/ais/aiId/listings/listingId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.listings.updateListing({
            aiId: "aiId",
            listingId: "listingId",
            expectedRevision: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateListing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { expectedRevision: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/listings/listingId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.updateListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("updateListing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { expectedRevision: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/listings/listingId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.updateListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("updateListing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { expectedRevision: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/listings/listingId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.updateListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("updateListing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { expectedRevision: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/listings/listingId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.updateListing({
                aiId: "aiId",
                listingId: "listingId",
                expectedRevision: 1,
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("batchUpsertListings (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { listings: [{ type: "PRODUCT", title: "title" }] };
        const rawResponseBody = { results: [{ key: "value" }] };

        server
            .mockEndpoint()
            .post("/ais/aiId/listings/batch-upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.listings.batchUpsertListings({
            aiId: "aiId",
            listings: [
                {
                    type: "PRODUCT",
                    title: "title",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("batchUpsertListings (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            listings: [
                { type: "PRODUCT", title: "x" },
                { type: "PRODUCT", title: "x" },
            ],
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings/batch-upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.batchUpsertListings({
                aiId: "aiId",
                listings: [
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("batchUpsertListings (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            listings: [
                { type: "PRODUCT", title: "x" },
                { type: "PRODUCT", title: "x" },
            ],
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings/batch-upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.batchUpsertListings({
                aiId: "aiId",
                listings: [
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("batchUpsertListings (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            listings: [
                { type: "PRODUCT", title: "x" },
                { type: "PRODUCT", title: "x" },
            ],
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings/batch-upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.batchUpsertListings({
                aiId: "aiId",
                listings: [
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("batchUpsertListings (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            listings: [
                { type: "PRODUCT", title: "x" },
                { type: "PRODUCT", title: "x" },
            ],
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listings/batch-upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.batchUpsertListings({
                aiId: "aiId",
                listings: [
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                    {
                        type: "PRODUCT",
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createListingImport (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "CSV" };
        const rawResponseBody = {
            listingImport: {
                id: "id",
                aiId: "aiId",
                kind: "CSV",
                status: "QUEUED",
                processedRows: 1,
                successfulRows: 1,
                failedRows: 1,
                errorObjectKey: "errorObjectKey",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/ais/aiId/listing-imports")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.listings.createListingImport({
            "Idempotency-Key": "Idempotency-Key",
            aiId: "aiId",
            kind: "CSV",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createListingImport (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "CSV" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listing-imports")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListingImport({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                kind: "CSV",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createListingImport (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "CSV" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listing-imports")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListingImport({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                kind: "CSV",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createListingImport (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "CSV" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listing-imports")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListingImport({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                kind: "CSV",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createListingImport (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "CSV" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/listing-imports")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listings.createListingImport({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                kind: "CSV",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
