// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../src/api/index";
import { DarwinClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SkillsClient", () => {
    test("listAISkills (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            skills: [
                {
                    id: "id",
                    aiId: "aiId",
                    name: "name",
                    slug: "slug",
                    description: "description",
                    category: "ai",
                    source: "source",
                    visibility: "PRIVATE",
                    status: "status",
                    enabled: true,
                    executable: true,
                    enabledActions: ["enabledActions"],
                    instructions: "instructions",
                    version: 1,
                    versionId: "versionId",
                    metadata: { key: "value" },
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/ais/aiId/skills").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.skills.listAiSkills({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listAISkills (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/skills").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.listAiSkills({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listAISkills (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/skills").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.listAiSkills({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listAISkills (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/skills").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.listAiSkills({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listAISkills (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/skills").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.listAiSkills({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createAISkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            skill: {
                id: "id",
                aiId: "aiId",
                name: "name",
                slug: "slug",
                description: "description",
                category: "ai",
                source: "source",
                visibility: "PRIVATE",
                status: "status",
                enabled: true,
                executable: true,
                enabledActions: ["enabledActions"],
                instructions: "instructions",
                version: 1,
                versionId: "versionId",
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/ais/aiId/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.createAiSkill({
            aiId: "aiId",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAISkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createAiSkill({
                aiId: "aiId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createAISkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createAiSkill({
                aiId: "aiId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createAISkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createAiSkill({
                aiId: "aiId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createAISkill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createAiSkill({
                aiId: "aiId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("deleteAISkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { skill: { id: "id", status: "archived" } };

        server
            .mockEndpoint()
            .delete("/ais/aiId/skills/skillId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.deleteAiSkill({
            aiId: "aiId",
            skillId: "skillId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteAISkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/skills/skillId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.deleteAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("deleteAISkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/skills/skillId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.deleteAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("deleteAISkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/skills/skillId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.deleteAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("deleteAISkill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/ais/aiId/skills/skillId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.deleteAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("updateAISkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            skill: {
                id: "id",
                aiId: "aiId",
                name: "name",
                slug: "slug",
                description: "description",
                category: "ai",
                source: "source",
                visibility: "PRIVATE",
                status: "status",
                enabled: true,
                executable: true,
                enabledActions: ["enabledActions"],
                instructions: "instructions",
                version: 1,
                versionId: "versionId",
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/ais/aiId/skills/skillId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.updateAiSkill({
            aiId: "aiId",
            skillId: "skillId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAISkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/skills/skillId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.updateAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("updateAISkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/skills/skillId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.updateAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("updateAISkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/skills/skillId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.updateAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("updateAISkill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/skills/skillId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.updateAiSkill({
                aiId: "aiId",
                skillId: "skillId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
