// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../src/api/index";
import { DarwinClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UsageClient", () => {
    test("getAIUsage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            usage: {
                aiId: "aiId",
                aiUsage: { currency: "usd", capturedMinor: 1, reservedMinor: 1 },
                wallet: { key: "value" },
                activeGoals: 1,
                activeDeals: 1,
            },
        };

        server.mockEndpoint().get("/ais/aiId/usage").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.usage.getAiUsage({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAIUsage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/usage").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.usage.getAiUsage({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getAIUsage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/usage").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.usage.getAiUsage({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getAIUsage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/usage").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.usage.getAiUsage({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getAIUsage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/usage").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.usage.getAiUsage({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
