// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         content: "content"
 *     }
 */
export interface CreateAgentMessageRequest {
    content: string;
    /** An optional caller-generated idempotency and correlation identifier. */
    requestId?: string;
}
